"""baseline

Revision ID: e287169df13c
Revises: 
Create Date: 2026-06-14 09:59:58.357505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# EnumValueType is a TypeDecorator whose impl is String — at the DDL level these
# columns are plain VARCHAR(length) with no DB-level enum constraint. Render them
# as sa.String in migrations to avoid importing app-layer enum classes here.
EnumValueType = lambda **kw: sa.String(length=kw.get("length"))


# revision identifiers, used by Alembic.
revision: str = 'e287169df13c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_ids', sa.JSON(), nullable=False),
    sa.Column('skipped_inflight_ids', sa.JSON(), nullable=False),
    sa.Column('analyzed_ids', sa.JSON(), nullable=False),
    sa.Column('failed_ids', sa.JSON(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_analysis_jobs_status_queued', ['status', 'queued_at'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True, comment='Comma-separated keywords for fallback matching'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_auto_created', sa.Boolean(), nullable=False, comment='True if discovered by LLM'),
    sa.Column('content_count', sa.Integer(), nullable=False, comment='Denormalized count for sorting'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('weekday', sa.String(length=10), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('cutoff_at', sa.DateTime(), nullable=False),
    sa.Column('source_scope', sa.String(length=20), nullable=False),
    sa.Column('source_item_ids', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('takeaway', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('trends', sa.Text(), nullable=True),
    sa.Column('top_picks', sa.Text(), nullable=True),
    sa.Column('platform_tips', sa.Text(), nullable=True),
    sa.Column('topic_count', sa.Integer(), nullable=False),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'edition', 'cutoff_at', name='uq_daily_report_version')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_cutoff_at'), ['cutoff_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_edition'), ['edition'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=False)

    op.create_table('fanqie_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=50), nullable=False),
    sa.Column('book_name', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('thumb_uri', sa.String(length=1000), nullable=True),
    sa.Column('read_count', sa.String(length=50), nullable=True),
    sa.Column('word_number', sa.String(length=50), nullable=True),
    sa.Column('last_chapter_title', sa.String(length=500), nullable=True),
    sa.Column('last_chapter_update_time', sa.Integer(), nullable=True),
    sa.Column('current_pos', sa.Integer(), nullable=False),
    sa.Column('rank_type', sa.String(length=30), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('male_reading_pos', sa.Integer(), nullable=True),
    sa.Column('male_new_pos', sa.Integer(), nullable=True),
    sa.Column('female_reading_pos', sa.Integer(), nullable=True),
    sa.Column('female_new_pos', sa.Integer(), nullable=True),
    sa.Column('rank_pos_diff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    with op.batch_alter_table('fanqie_books', schema=None) as batch_op:
        batch_op.create_index('ix_fanqie_book_cat', ['category_id'], unique=False)
        batch_op.create_index('ix_fanqie_book_ranktype', ['rank_type'], unique=False)

    op.create_table('fanqie_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fanqie_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fanqie_id')
    )
    with op.batch_alter_table('fanqie_categories', schema=None) as batch_op:
        batch_op.create_index('ix_fanqie_cat_group', ['group'], unique=False)

    op.create_table('fanqie_rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('book_id', sa.String(length=50), nullable=False),
    sa.Column('book_name', sa.String(length=500), nullable=False),
    sa.Column('rank_type', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('read_count', sa.String(length=50), nullable=True),
    sa.Column('word_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fanqie_rank_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snap_book', ['book_id'], unique=False)
        batch_op.create_index('ix_snap_date_type', ['snapshot_date', 'rank_type'], unique=False)

    op.create_table('job_execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='RUNNING / SUCCESS / FAILED / TIMEOUT / SKIPPED'),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='执行耗时(毫秒)'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='成功时输出摘要'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时错误信息'),
    sa.Column('trigger_type', sa.String(length=20), nullable=True, comment='scheduler / manual'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_execution_logs', schema=None) as batch_op:
        batch_op.create_index('ix_job_exec_logs_job_key_started', ['job_key', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_execution_logs_job_key'), ['job_key'], unique=False)

    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('request_model', sa.String(length=200), nullable=True),
    sa.Column('actual_model', sa.String(length=200), nullable=True),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('billable_input_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('cache_read_cost', sa.Float(), nullable=False),
    sa.Column('cache_creation_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_1m_input', sa.Float(), nullable=True),
    sa.Column('cost_per_1m_output', sa.Float(), nullable=True),
    sa.Column('cost_per_1m_input_cache_hit', sa.Float(), nullable=True),
    sa.Column('cost_per_1m_input_cache_create', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_llm_call_logs_model_created', ['model_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_scene'), ['scene'], unique=False)
        batch_op.create_index('ix_llm_call_logs_scene_created', ['scene', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_status'), ['status'], unique=False)

    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eval_run_id', sa.String(length=50), nullable=False, comment='测评批次ID'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='关联 llm_models.id'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='快照模型名'),
    sa.Column('prompt_type', sa.String(length=50), nullable=False, comment='测评类型: analysis/daily_report/weekly_digest/classification'),
    sa.Column('prompt_text', sa.Text(), nullable=True, comment='使用的 prompt (可选存储)'),
    sa.Column('response_text', sa.Text(), nullable=True, comment='模型输出'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='响应耗时(毫秒)'),
    sa.Column('tokens_input', sa.Integer(), nullable=True, comment='输入 token 数'),
    sa.Column('tokens_output', sa.Integer(), nullable=True, comment='输出 token 数'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='人工打分 1-5'),
    sa.Column('auto_score', sa.Float(), nullable=True, comment='自动评分'),
    sa.Column('notes', sa.Text(), nullable=True, comment='人工备注'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING/RUNNING/DONE/FAILED'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_model_evals_run_type', ['eval_run_id', 'prompt_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_evaluations_eval_run_id'), ['eval_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_evaluations_model_id'), ['model_id'], unique=False)

    op.create_table('monthly_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('month_label', sa.String(length=30), nullable=False),
    sa.Column('month_start', sa.String(length=10), nullable=False),
    sa.Column('month_end', sa.String(length=10), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('takeaway', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('trends', sa.Text(), nullable=True),
    sa.Column('top_picks', sa.Text(), nullable=True),
    sa.Column('category_summary', sa.Text(), nullable=True),
    sa.Column('platform_tips', sa.Text(), nullable=True),
    sa.Column('topic_clusters', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_digests_month_key'), ['month_key'], unique=True)

    op.create_table('mother_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('target_reader', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mother_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mother_topics_name'), ['name'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_cat', ['category'], unique=False)
        batch_op.create_index('ix_notif_read', ['is_read'], unique=False)

    op.create_table('qimao_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('category1_name', sa.String(length=100), nullable=True),
    sa.Column('category2_name', sa.String(length=100), nullable=True),
    sa.Column('thumb_uri', sa.String(length=1000), nullable=True),
    sa.Column('words_num', sa.String(length=50), nullable=True),
    sa.Column('collect_count', sa.Integer(), nullable=True),
    sa.Column('latest_chapter_id', sa.String(length=50), nullable=True),
    sa.Column('latest_chapter_title', sa.String(length=500), nullable=True),
    sa.Column('update_time', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_over', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Integer(), nullable=True),
    sa.Column('is_continue_top', sa.Integer(), nullable=True),
    sa.Column('index_change', sa.Integer(), nullable=True),
    sa.Column('surge_rank', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('rank_type', sa.String(length=20), nullable=False),
    sa.Column('date_type', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qimao_books', schema=None) as batch_op:
        batch_op.create_index('ix_qimao_book', ['book_id'], unique=False)
        batch_op.create_index('ix_qimao_channel_rank', ['channel', 'rank_type'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_key', sa.String(length=100), nullable=False, comment='唯一任务标识'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('job_type', sa.String(length=50), nullable=False, comment='cron / interval'),
    sa.Column('cron_expr', sa.String(length=100), nullable=True, comment='cron 表达式'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='interval 间隔秒数'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_jobs_enabled', ['enabled'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', EnumValueType(length=10), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', EnumValueType(length=8), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='话题名称（LLM 生成）'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='关键标签列表'),
    sa.Column('summary', sa.Text(), nullable=True, comment='话题一句话摘要'),
    sa.Column('content_count', sa.Integer(), nullable=True, comment='话题下内容数'),
    sa.Column('best_score', sa.Float(), nullable=True, comment='话题内最高精选分'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(length=200), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.Column('top_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_trends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_trends_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_trends_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_trends_topic_id'), ['topic_id'], unique=False)

    op.create_table('trending_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', EnumValueType(length=12), nullable=False),
    sa.Column('category', EnumValueType(length=13), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('hot_value', sa.Integer(), nullable=False),
    sa.Column('hot_value_raw', sa.String(length=100), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trending_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trending_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trending_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_trending_items_source'), ['source'], unique=False)

    op.create_table('trending_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_hour', sa.Integer(), nullable=False),
    sa.Column('source', EnumValueType(length=12), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trending_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trending_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('weekly_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_key', sa.String(length=20), nullable=False),
    sa.Column('week_label', sa.String(length=50), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('week_end', sa.String(length=10), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('takeaway', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('trends', sa.Text(), nullable=True),
    sa.Column('top_picks', sa.Text(), nullable=True),
    sa.Column('category_summary', sa.Text(), nullable=True),
    sa.Column('platform_tips', sa.Text(), nullable=True),
    sa.Column('topic_clusters', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_digests_week_key'), ['week_key'], unique=True)

    op.create_table('zhihu_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('sort_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('author_desc', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('thumb_url', sa.String(length=1000), nullable=True),
    sa.Column('category1_name', sa.String(length=100), nullable=False),
    sa.Column('category2_name', sa.String(length=100), nullable=True),
    sa.Column('chapter_text', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=False),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('is_svip', sa.Boolean(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('online_time', sa.Integer(), nullable=True),
    sa.Column('online_time_text', sa.String(length=100), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('subscription_name', sa.String(length=50), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('business_line', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rank_pos_diff', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sort_type', name='uq_zhihu_albums_bid_sort')
    )
    with op.batch_alter_table('zhihu_albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zhihu_albums_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_albums_category1_name'), ['category1_name'], unique=False)
        batch_op.create_index('ix_zhihu_albums_category1_sort', ['category1_name', 'sort_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_albums_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_albums_position'), ['position'], unique=False)
        batch_op.create_index('ix_zhihu_albums_sort_pos', ['sort_type', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_albums_sort_type'), ['sort_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_albums_title'), ['title'], unique=False)

    op.create_table('zhihu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zhihu_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('artwork', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zhihu_categories', schema=None) as batch_op:
        batch_op.create_index('ix_zhihu_cat_parent', ['parent_id', 'sort'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_categories_zhihu_id'), ['zhihu_id'], unique=True)

    op.create_table('zhihu_rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('sort_type', sa.String(length=50), nullable=False),
    sa.Column('category1_name', sa.String(length=100), nullable=True),
    sa.Column('category2_id', sa.String(length=50), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zhihu_rank_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zhihu_rank_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_zhihu_rank_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('content_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', EnumValueType(length=9), nullable=False),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of', sa.Integer(), nullable=True, comment='Points to canonical item if duplicate'),
    sa.Column('similarity_score', sa.Float(), nullable=True, comment='Similarity score to group representative'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_content_hash'), ['content_hash'], unique=False)

    op.create_table('favorite_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', EnumValueType(length=11), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', EnumValueType(length=11), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_key', name='uq_favorite_user_target')
    )
    with op.batch_alter_table('favorite_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_favorite_items_user_status_created', ['user_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_favorite_items_user_status_position', ['user_id', 'status', 'position'], unique=False)
        batch_op.create_index('ix_favorite_items_user_type_created', ['user_id', 'target_type', 'created_at'], unique=False)

    op.create_table('issue_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('severity', EnumValueType(length=8), nullable=False),
    sa.Column('status', EnumValueType(length=11), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('fixed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_issue_feedback_severity_created', ['severity', 'created_at'], unique=False)
        batch_op.create_index('ix_issue_feedback_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_issue_feedback_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名称，如 GLM-5.1'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='litellm provider: openai / custom_zhipu …'),
    sa.Column('model_id', sa.String(length=200), nullable=False, comment='litellm model string: openai/glm-5.1'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API Key (加密存储)'),
    sa.Column('api_base', sa.String(length=500), nullable=True, comment='自定义 API endpoint'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('routing_group', sa.String(length=50), nullable=False, comment='运行时路由组'),
    sa.Column('model_family', sa.String(length=50), nullable=True, comment='模型家族，如 deepseek/qwen/glm'),
    sa.Column('channel_name', sa.String(length=100), nullable=True, comment='渠道名，如 official/opencode/openrouter'),
    sa.Column('routing_priority', sa.Integer(), nullable=False, comment='路由优先级，数字越小越先尝试'),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False, comment='失败后冷却秒数'),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=True, comment='每1k input token 成本(元)'),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=True, comment='每1k output token 成本(元)'),
    sa.Column('extra_params', sa.JSON(), nullable=True, comment='额外参数(JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.create_index('ix_llm_models_enabled', ['enabled'], unique=False)
        batch_op.create_index('ix_llm_models_owner_route', ['owner_user_id', 'routing_group', 'routing_priority'], unique=False)
        batch_op.create_index('ix_llm_models_route', ['routing_group', 'routing_priority'], unique=False)

    op.create_table('product_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', EnumValueType(length=11), nullable=False),
    sa.Column('status', EnumValueType(length=11), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_updates', schema=None) as batch_op:
        batch_op.create_index('ix_product_updates_kind_status', ['kind', 'status'], unique=False)
        batch_op.create_index('ix_product_updates_shipped_at', ['shipped_at'], unique=False)
        batch_op.create_index('ix_product_updates_status_created', ['status', 'created_at'], unique=False)

    op.create_table('user_integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_integrations_user_provider')
    )
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.create_index('ix_user_integrations_user_provider', ['user_id', 'provider'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_user_sessions_token_active', ['token_hash', 'revoked_at'], unique=False)
        batch_op.create_index('ix_user_sessions_user_expires', ['user_id', 'expires_at'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('hot_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('creator_score', sa.Float(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('platform_fit', sa.JSON(), nullable=True),
    sa.Column('recommended_reason', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('audience_emotion', sa.Text(), nullable=True),
    sa.Column('creator_angles', sa.JSON(), nullable=True),
    sa.Column('title_suggestions', sa.JSON(), nullable=True),
    sa.Column('outline_suggestions', sa.JSON(), nullable=True),
    sa.Column('xiaohongshu_plan', sa.JSON(), nullable=True),
    sa.Column('short_video_plan', sa.JSON(), nullable=True),
    sa.Column('risk_notes', sa.JSON(), nullable=True),
    sa.Column('curation_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('source_weight', sa.Float(), nullable=True),
    sa.Column('info_density', sa.Float(), nullable=True),
    sa.Column('actionability', sa.Float(), nullable=True),
    sa.Column('analysis_mode', sa.Text(), nullable=True),
    sa.Column('prescreen_model', sa.Text(), nullable=True),
    sa.Column('final_model', sa.Text(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('prescreen_confidence', sa.Float(), nullable=True),
    sa.Column('prescreen_score', sa.Float(), nullable=True),
    sa.Column('enrichment_status', sa.Text(), nullable=True),
    sa.Column('enrichment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('explosion_ratio', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ignored_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', name='uq_ignored_content')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', EnumValueType(length=12), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'user_id', name='uq_user_feedback_content_user')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_user_feedback_content_user', ['content_id', 'user_id'], unique=False)
        batch_op.create_index('ix_user_feedback_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_user_feedback_user_created')
        batch_op.drop_index('ix_user_feedback_content_user')

    op.drop_table('user_feedback')
    op.drop_table('ignored_items')
    op.drop_table('content_metrics')
    op.drop_table('ai_analyses')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_expires')
        batch_op.drop_index('ix_user_sessions_token_active')

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_user_integrations_user_provider')

    op.drop_table('user_integrations')
    with op.batch_alter_table('product_updates', schema=None) as batch_op:
        batch_op.drop_index('ix_product_updates_status_created')
        batch_op.drop_index('ix_product_updates_shipped_at')
        batch_op.drop_index('ix_product_updates_kind_status')

    op.drop_table('product_updates')
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_models_route')
        batch_op.drop_index('ix_llm_models_owner_route')
        batch_op.drop_index('ix_llm_models_enabled')

    op.drop_table('llm_models')
    with op.batch_alter_table('issue_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_issue_feedback_user_created')
        batch_op.drop_index('ix_issue_feedback_status_created')
        batch_op.drop_index('ix_issue_feedback_severity_created')

    op.drop_table('issue_feedback')
    with op.batch_alter_table('favorite_items', schema=None) as batch_op:
        batch_op.drop_index('ix_favorite_items_user_type_created')
        batch_op.drop_index('ix_favorite_items_user_status_position')
        batch_op.drop_index('ix_favorite_items_user_status_created')
        batch_op.drop_index(batch_op.f('ix_favorite_items_user_id'))

    op.drop_table('favorite_items')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_content_hash'))

    op.drop_table('content_items')
    with op.batch_alter_table('zhihu_rank_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zhihu_rank_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_zhihu_rank_snapshots_created_at'))

    op.drop_table('zhihu_rank_snapshots')
    with op.batch_alter_table('zhihu_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zhihu_categories_zhihu_id'))
        batch_op.drop_index(batch_op.f('ix_zhihu_categories_parent_id'))
        batch_op.drop_index('ix_zhihu_cat_parent')

    op.drop_table('zhihu_categories')
    with op.batch_alter_table('zhihu_albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zhihu_albums_title'))
        batch_op.drop_index(batch_op.f('ix_zhihu_albums_sort_type'))
        batch_op.drop_index('ix_zhihu_albums_sort_pos')
        batch_op.drop_index(batch_op.f('ix_zhihu_albums_position'))
        batch_op.drop_index(batch_op.f('ix_zhihu_albums_created_at'))
        batch_op.drop_index('ix_zhihu_albums_category1_sort')
        batch_op.drop_index(batch_op.f('ix_zhihu_albums_category1_name'))
        batch_op.drop_index(batch_op.f('ix_zhihu_albums_business_id'))

    op.drop_table('zhihu_albums')
    with op.batch_alter_table('weekly_digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_digests_week_key'))

    op.drop_table('weekly_digests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trending_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trending_snapshots_snapshot_date'))

    op.drop_table('trending_snapshots')
    with op.batch_alter_table('trending_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trending_items_source'))
        batch_op.drop_index(batch_op.f('ix_trending_items_category'))
        batch_op.drop_index(batch_op.f('ix_trending_items_batch_id'))

    op.drop_table('trending_items')
    with op.batch_alter_table('topic_trends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_trends_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_trends_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_topic_trends_keyword'))

    op.drop_table('topic_trends')
    op.drop_table('topic_groups')
    op.drop_table('sources')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_jobs_enabled')

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('qimao_books', schema=None) as batch_op:
        batch_op.drop_index('ix_qimao_channel_rank')
        batch_op.drop_index('ix_qimao_book')

    op.drop_table('qimao_books')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_read')
        batch_op.drop_index('ix_notif_cat')

    op.drop_table('notifications')
    with op.batch_alter_table('mother_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mother_topics_name'))

    op.drop_table('mother_topics')
    with op.batch_alter_table('monthly_digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_digests_month_key'))

    op.drop_table('monthly_digests')
    with op.batch_alter_table('model_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_evaluations_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_evaluations_eval_run_id'))
        batch_op.drop_index('ix_model_evals_run_type')

    op.drop_table('model_evaluations')
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_status'))
        batch_op.drop_index('ix_llm_call_logs_scene_created')
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_scene'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_model_id'))
        batch_op.drop_index('ix_llm_call_logs_model_created')
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_created_at'))

    op.drop_table('llm_call_logs')
    with op.batch_alter_table('job_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_execution_logs_job_key'))
        batch_op.drop_index('ix_job_exec_logs_job_key_started')

    op.drop_table('job_execution_logs')
    with op.batch_alter_table('fanqie_rank_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snap_date_type')
        batch_op.drop_index('ix_snap_book')

    op.drop_table('fanqie_rank_snapshots')
    with op.batch_alter_table('fanqie_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_fanqie_cat_group')

    op.drop_table('fanqie_categories')
    with op.batch_alter_table('fanqie_books', schema=None) as batch_op:
        batch_op.drop_index('ix_fanqie_book_ranktype')
        batch_op.drop_index('ix_fanqie_book_cat')

    op.drop_table('fanqie_books')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_edition'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_cutoff_at'))

    op.drop_table('daily_reports')
    op.drop_table('categories')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_jobs_status_queued')
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_status'))

    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
